version: '2.0'

services:
  jupyrun_db:
    image: jupyrun_db:latest 

    restart: unless-stopped

    environment:
      DUMMY: 1

    build:
      context: .
      dockerfile: deploy/main/Dockerfile

    volumes:
      # - "C:/Users/tglaubach/Nextcloud/davmount/skampieng_db/jupyrun_db:/home/jovyan/db:rw"
      # - "C:/Users/tglaubach/Nextcloud/davmount/skampieng_db/jupyrun_shared:/home/jovyan/shared:rw"
      - /var/jupyrun/db:/home/jovyan/db:rw
      - /var/jupyrun/shared:/home/jovyan/shared:rw

    ports:
      - "7990:8080"

    command: fastapi run main.py --port 8080
    
  jupyrun_proc:
    restart: unless-stopped
    build:
      context: .
      dockerfile: deploy/procserver/Dockerfile
    image: "jupyrun_proc:latest"
    volumes:
      - /var/jupyrun/db:/home/jovyan/db:rw
      - /var/jupyrun/shared:/home/jovyan/shared:rw

      # - "C:/Users/tglaubach/Nextcloud/davmount/skampieng_db/jupyrun_db:/home/jovyan/db:rw"
      # - "C:/Users/tglaubach/Nextcloud/davmount/skampieng_db/jupyrun_shared:/home/jovyan/shared:rw"

    environment:
      HOME: /home/jovyan
      JUPYTER_TOKEN: "jupyrun"
      SHARED: /home/jovyan/shared
      PYTHONPATH: "/home/jovyan/shared/libs"
    command: "python3 procserver.py"
    depends_on:
      - jupyrun_db
  

  jupyter:
    depends_on:
        - jupyrun_proc
    image: jupyrun_proc:latest
    ports: 
      - "7991:8888"
    volumes:
      - /var/jupyrun/shared:/home/jovyan/shared:rw
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "jupyrun"
      PYTHONPATH: "/home/jovyan/shared/libs"